FROM node:argon

ENV PORT 80
ENV NODE_ENV production
ENV dbURI mongodb://mongo:27017/pokerPlanning

RUN mkdir -p /app/bin/
WORKDIR /app/

COPY package.json /app/
COPY makefile /app/
COPY gulpfile.js /app/
COPY tsconfig.json /app/
COPY typings.json /app/

COPY src /app/src

RUN npm install typescript -g lol
RUN npm install typings -g
RUN npm install gulp -g
RUN npm install

RUN npm install gulp
RUN npm install gulp-sass
RUN npm install @types/core-js
RUN npm install run-sequence

RUN typings install

COPY typings/index.d.ts /app/typings/
COPY typings/manual /app/typings/manual

RUN make build

EXPOSE 80

CMD ["node" , "./bin/server/server.js"]